services:
  # MongoDB Service
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: restaurant-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=restaurant
    volumes:
      - mongodb_data:/data/db
    networks:
      - restaurant-network
    restart: unless-stopped

  # n8n Service
  n8n:
    build: ./n8n
    container_name: restaurant-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - DB_TYPE=sqlite
      - N8N_ENCRYPTION_KEY=restaurant_encryption_key_2024
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      # Ngrok environment variables for external access
      - EDITOR_BASE_URL=https://inspectorial-daniele-multifocal.ngrok-free.dev 
      - WEBHOOK_URL=https://inspectorial-daniele-multifocal.ngrok-free.dev 
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_COMMUNITY_PACKAGES_ALLOWED=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./scripts:/scripts
      - ./temp-repo:/app
    depends_on:
      - mongodb
    networks:
      - restaurant-network
    restart: unless-stopped
  # Node.js App Service
  node-app:
    image: node:18-alpine
    container_name: restaurant-node-app
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./node-app:/app
      - ./scripts:/scripts
    environment:
      - MONGO_URI=mongodb://mongodb:27017/restaurant
      - JWT_SECRET=supersecretkey
      - PORT=3000
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - restaurant-network
    command: npm start
    restart: unless-stopped

volumes:
  mongodb_data:
  n8n_data:

networks:
  restaurant-network:
    driver: bridge